language: python
python:
  - "3.4"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
#

# Setup anaconda
before_install:
  - pip install pip --upgrade
  - pip install -r requirements.txt
  - pip install pytest==2.7.3 -I
  - pip install pytest-cov
  - pip install python-coveralls
# Install packages
install:
  - python setup.py install
# command to run tests, e.g. python setup.py test
script:  
  - py.test  tests -v 
after_sucess:
  - coveralls
