# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Beer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Beer, a Python package -- now PEP8 compliant!
baseurl: "/Beer" # the subpath of your site, e.g. /blog
url: "http://www.hackeyhour.org" # the base hostname & protocol for your site
twitter_username: CSciBio
github_username: schae234

# Build settings
markdown: kramdown
